### ISSUE TITLE
Dropzone example code not working when first dropzone is empty

### ISSUE THREAD

**Issue by alexander-schranz** [alexander-schranz/sulu-form-bundle#125]
The following line is not correct as it will not work when `this.dropzones[0]` has no files.

```js
this.dropzones[0].processQueue();
```

https://github.com/alexander-schranz/sulu-form-bundle/blob/827f78be02ad865ae61104d6249f0d04b28e12f0/Resources/doc/dropzone.md

**Comment by thomasduenser** [comment]
As this line is only called when there are files, I would replace it with this:

```js
for (var i = 0, length = this.dropzones.length; i < length; i++) {
    if (this.dropzones[i].getQueuedFiles().length) {
        this.dropzones[i].processQueue();
        return true;
    }
}
```

This processes the queue for the first dropzone which has files. Should it be `return true;` or `break;`?

**Comment by thomasduenser** [comment]
Furthermore, the `for-loop` in `sendingDropzone` should be modified to something like:

```js
for (var i = 0, length = this.dropzones.length; i < length; i++) {
    var files = this.dropzones[i].getQueuedFiles();

    // Append files only if it's not the same dropzone.
    if (files.length && files[0].name !== data[0].name) {
        for (var x = 0, fileLength = files.length; x < fileLength; x++) {
            formData.append(
                this.dropzones[i]._getParamName(x),
                files[x],
                files[x].name
            );
        }
    }
}
```

This sends only the current dropzone and appends only the files from other dropzones if available.

**Comment by alexander-schranz** [comment]
@thomasduenser it need to be a `break;` a return true would do a normal submit of a page thats why currently a return false is after it.

did edit your post always set a programming language when add code with markdown:

``````markdown
```js
// some code
```
``````
