### ISSUE TITLE
Wrong/Missing locale when viewing in backend

### ISSUE THREAD

**Issue by thomasduenser** [alexander-schranz/sulu-form-bundle#129]
After installing the bundle and following the README which includes the permission part, there was following error when clicking on the Form Icon in the Sulu Backend Navigation, produced from the URL `/admin/api/l91/forms/fields`.

```
Permission "view" in localization "en" for object with id "" and of type "" not granted
```

The project does only have `de` as locale. Parameter `locale`seems to be missing for the URL call, because right now it uses the locale, defined in `app/config/config.yml`.

**Comment by alexander-schranz** [comment]
here seems the locale missing in the fields url.
The correct  url should be: `/admin/api/l91/forms/fields?locale=de`
`de` needs to be the locale from the require route definition.
