### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by RaphaelHofer** [alexander-schranz/sulu-form-bundle#32]
- [x] add parameters in parameters.yml
- [x] add php class for entity because it is not generated automatically

These two points are missing in the documentation, for a newcomer :)

greetings,
raphael

**Comment by alexander-schranz** [comment]
`add php class for entity because it is not generated automatically` fixed in sulu/sulu

**Comment by alexander-schranz** [comment]
fixed by using exist parameter from sulu
