### ISSUE TITLE
"Free text" field type includes redundant option

### ISSUE THREAD

**Issue by TomSeldon** [alexander-schranz/sulu-form-bundle#88]
Minor bug.

When building a dynamic form and choosing to use a "free text" field, there is an option to set it as a required field.

This doesn't really make sense as it's a piece of hard-coded text set by an Administrator.

![screen shot 2016-09-09 at 10 15 24](https://cloud.githubusercontent.com/assets/3420620/18381947/a71c8ee2-7676-11e6-93c1-6b80958e2284.png)

**Comment by alexander-schranz** [comment]
fixed in the clean up #92
