### ISSUE TITLE
Feature request: Rich content field for dynamic forms

### ISSUE THREAD

**Issue by TomSeldon** [alexander-schranz/sulu-form-bundle#89]
## Feature request

There's currently a "free text" field when creating a dynamic form. It'd be really useful if this field, or another like it (to avoid a breaking change), could be used with the rich content editor. 

Specifically I'd like Administrators to be able to include text in certain places of a form that include links to other pages on the site. Having the rich content editor available as a custom form field would mean they'd be able to use the single internal link editor plugin.

**Comment by alexander-schranz** [comment]
currently only implemented in: https://github.com/sulu/SuluFormBundle/pull/5. In this repo I will finish all issues tag on `1.0` and then only support bugfixes here. Currently the sulu bundle is heavy in development and should not be used before a tagged version. There will come a migration script to migrate from this repo to the new: https://github.com/sulu/SuluFormBundle/issues/12.

**Comment by alexander-schranz** [comment]
will not be implemented here use the new version from https://github.com/sulu/SuluFormBundle instead
